### ISSUE TITLE
Added Custom Adapter but Recycler doesn't show

### ISSUE THREAD

**Issue by zipitup** [Jintin/MixAdapter#1]
```
mAdapter = new AddOrderAdapter(mQuery);
mAdapter2 = new AddOrderAdapter(mQuery2);

MixAdapter<RecyclerView.ViewHolder> adapter = new MixAdapter<>();
adapter.addAdapter(mAdapter);
adapter.addAdapter(mAdapter2);

mAddOrderRecycler.setLayoutManager(new LinearLayoutManager(this));
mAddOrderRecycler.setAdapter(adapter);
```

I did this but recyclerview shows up empty. How do I check what's wrong?

**Comment by Jintin** [comment]
You can debug the size of adapter first. check `getItemCount` both on `MixAdapter ` and `AddOrderAdapter `

**Comment by zipitup** [comment]
I get 0 of AddOrderAdapter.itemcount. But if I made it to a single adapter (remove MixAdapter) - the count is still 0. But the recyclerview shows up fine.

```
        mAddOrderRecycler.setLayoutManager(new LinearLayoutManager(this));
        mAddOrderRecycler.setAdapter(mAdapter);

        int itemCount = mAdapter.getItemCount();
        Log.d(TAG, String.valueOf(itemCount));
```

**Comment by zipitup** [comment]
[https://stackoverflow.com/questions/37937497/getitemcount-on-adapter-is-returning-0](url)

I just read this. I'm using Firebase's Firestore, that's probably why.

Does the plugin work with Firebase?

**Comment by Jintin** [comment]
Sorry.
I think currently not support, maybe I'll find out how to integrate with it in the future.
